In [4]:
import numpy as np
import pandas as pd

In [7]:
df1 = pd.read_csv("Reisgo_cred_LIMPIO.csv")

In [8]:
df1.head()

Age  Annual_Income  Num_Credit_Card  Num_Bank_Accounts  Num_of_Loan  \
0  0.710372      -0.204694        -0.187121          -0.175879    -0.173609   
1 -0.031721      -0.225162         0.172682          -0.035744     0.291409   
2  1.916273       0.158343        -0.331042          -0.129168    -0.251112   
3 -0.681052      -0.115497        -0.187121          -0.129168    -0.328615   
4  0.988657       0.022593        -0.331042          -0.362726    -0.251112   

   Delay_from_due_date  Credit_Utilization_Ratio  Outstanding_Debt  \
0             0.462555                 -0.544324         -0.776398   
1             0.798815                 -1.257592          2.960861   
2            -1.151493                 -0.225377         -0.517233   
3            -0.546225                  0.196653         -0.608686   
4            -0.747981                 -0.441456         -1.173592   

   Amount_invested_monthly  High_spent_Large_value_payments  ...  Journalist  \
0                -0.201907                                0  ...           0   
1                -0.262096                                0  ...           0   
2                 0.082155                                0  ...           0   
3                -0.079618                                0  ...           0   
4                -0.163640                                0  ...           0   

   Lawyer  Manager  Mechanic  Media_Manager  Musician  Scientist  Teacher  \
0       1        0         0              0         0          0        0   
1       0        0         0              0         1          0        0   
2       0        1         0              0         0          0        0   
3       0        0         0              0         0          0        1   
4       0        0         0              0         0          0        0   

   Writer  Credit_Score  
0       0             0  
1       0            -1  
2       0             0  
3       0             0  
4       0             0  

[5 rows x 31 columns]

In [9]:
df1.shape

(77874, 31)

#### Realizar CrossFeatures

In [13]:
import imblearn

In [14]:
from imblearn import over_sampling 
from imblearn.over_sampling import RandomOverSampler

In [15]:
dfCROSS= df1.drop('Credit_Score', axis=1, inplace=False)
y= df1[["Credit_Score"]]

In [16]:
dfCROSS.head()

Age  Annual_Income  Num_Credit_Card  Num_Bank_Accounts  Num_of_Loan  \
0  0.710372      -0.204694        -0.187121          -0.175879    -0.173609   
1 -0.031721      -0.225162         0.172682          -0.035744     0.291409   
2  1.916273       0.158343        -0.331042          -0.129168    -0.251112   
3 -0.681052      -0.115497        -0.187121          -0.129168    -0.328615   
4  0.988657       0.022593        -0.331042          -0.362726    -0.251112   

   Delay_from_due_date  Credit_Utilization_Ratio  Outstanding_Debt  \
0             0.462555                 -0.544324         -0.776398   
1             0.798815                 -1.257592          2.960861   
2            -1.151493                 -0.225377         -0.517233   
3            -0.546225                  0.196653         -0.608686   
4            -0.747981                 -0.441456         -1.173592   

   Amount_invested_monthly  High_spent_Large_value_payments  ...  \
0                -0.201907                                0  ...   
1                -0.262096                                0  ...   
2                 0.082155                                0  ...   
3                -0.079618                                0  ...   
4                -0.163640                                0  ...   

   Entrepreneur  Journalist  Lawyer  Manager  Mechanic  Media_Manager  \
0             0           0       1        0         0              0   
1             0           0       0        0         0              0   
2             0           0       0        1         0              0   
3             0           0       0        0         0              0   
4             0           0       0        0         0              0   

   Musician  Scientist  Teacher  Writer  
0         0          0        0       0  
1         1          0        0       0  
2         0          0        0       0  
3         0          0        1       0  
4         0          0        0       0  

[5 rows x 30 columns]

In [17]:
dfCROSS["AMD"]= dfCROSS["Amount_invested_monthly"]*(dfCROSS["Delay_from_due_date"])

dfCROSS["NND"]= dfCROSS["Num_of_Loan"]*(dfCROSS["Delay_from_due_date"])

dfCROSS["NNO"]= dfCROSS["Num_of_Loan"]*(dfCROSS["Outstanding_Debt"])

dfCROSS["AA"]= dfCROSS["Age"]/dfCROSS["Annual_Income"]

dfCROSS["NCD"]= (dfCROSS["Num_Bank_Accounts"]+dfCROSS["Num_Credit_Card"])/dfCROSS["Delay_from_due_date"]

dfCROSS["NCN"]= (dfCROSS["Num_Bank_Accounts"]+dfCROSS["Num_Credit_Card"])/dfCROSS["Num_of_Loan"]

dfCROSS["AD"]= dfCROSS["Annual_Income"]/dfCROSS["Delay_from_due_date"]

dfCROSS["AIxOD"]=dfCROSS["Annual_Income"] / dfCROSS["Outstanding_Debt"]

In [18]:
dfCROSS.head()

Age  Annual_Income  Num_Credit_Card  Num_Bank_Accounts  Num_of_Loan  \
0  0.710372      -0.204694        -0.187121          -0.175879    -0.173609   
1 -0.031721      -0.225162         0.172682          -0.035744     0.291409   
2  1.916273       0.158343        -0.331042          -0.129168    -0.251112   
3 -0.681052      -0.115497        -0.187121          -0.129168    -0.328615   
4  0.988657       0.022593        -0.331042          -0.362726    -0.251112   

   Delay_from_due_date  Credit_Utilization_Ratio  Outstanding_Debt  \
0             0.462555                 -0.544324         -0.776398   
1             0.798815                 -1.257592          2.960861   
2            -1.151493                 -0.225377         -0.517233   
3            -0.546225                  0.196653         -0.608686   
4            -0.747981                 -0.441456         -1.173592   

   Amount_invested_monthly  High_spent_Large_value_payments  ...  Teacher  \
0                -0.201907                                0  ...        0   
1                -0.262096                                0  ...        0   
2                 0.082155                                0  ...        0   
3                -0.079618                                0  ...        1   
4                -0.163640                                0  ...        0   

   Writer       AMD       NND       NNO         AA       NCD       NCN  \
0       0 -0.093393 -0.080304  0.134790  -3.470412 -0.784773  2.090907   
1       0 -0.209366  0.232782  0.862822   0.140881  0.171426  0.469915   
2       0 -0.094601  0.289154  0.129883  12.102036  0.399663  1.832687   
3       0  0.043489  0.179498  0.200023   5.896711  0.579044  0.962490   
4       0  0.122400  0.187827  0.294703  43.758808  0.927520  2.762783   

         AD     AIxOD  
0 -0.442529  0.263645  
1 -0.281871 -0.076046  
2 -0.137511 -0.306135  
3  0.211446  0.189748  
4 -0.030206 -0.019251  

[5 rows x 38 columns]

In [19]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier as rrr
from sklearn.ensemble import GradientBoostingClassifier as gbr
from sklearn.metrics import accuracy_score

In [20]:
X = dfCROSS.copy()
Y = y.copy() 

### Con Bosque y ROS

#### El ros mejora el 1 (good credscore) en el F1-score y minimamente el  -1

In [281]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    
    ros = RandomOverSampler(random_state=0)
    x_train,y_train = ros.fit_resample(x_train,y_train)
    
    RFR = rrr(max_depth=50, n_estimators=50).fit(x_train,y_train.values.ravel())
    print(RFR.score(x_train,y_train))
    print(RFR.score(x_test,y_test))


0.9997953163566311
0.7615763926342554
0.9998913043478261
0.7604977270976192
0.9997951387633611
0.7635025810925341


In [282]:
from sklearn.metrics import classification_report, confusion_matrix 
print(classification_report(y_test,RFR.predict(x_test)))
print(confusion_matrix(y_test,RFR.predict(x_test)))

              precision    recall  f1-score   support

          -1       0.76      0.80      0.78      7554
           0       0.79      0.77      0.78     13812
           1       0.70      0.68      0.69      4592

    accuracy                           0.76     25958
   macro avg       0.75      0.75      0.75     25958
weighted avg       0.76      0.76      0.76     25958

[[ 6014  1456    84]
 [ 1883 10673  1256]
 [   31  1429  3132]]


In [283]:
RFR.feature_importances_

array([0.03963895, 0.0505029 , 0.04119808, 0.05578945, 0.04123057,
       0.05722585, 0.04650088, 0.11963376, 0.04937306, 0.00540394,
       0.00637392, 0.00520168, 0.00494287, 0.00569439, 0.00709156,
       0.00376851, 0.00369294, 0.00399752, 0.00378499, 0.00371112,
       0.00403892, 0.00362935, 0.00389036, 0.00399067, 0.00394235,
       0.00365475, 0.00366116, 0.00408294, 0.00393006, 0.00420804,
       0.05840392, 0.0461065 , 0.05369859, 0.04569876, 0.05748205,
       0.04469911, 0.04395937, 0.05616614])

### Con Grad Boost Class y ROS 
##### Con Ros mejora el 1 (good cred score)

##### Max depth  = 41 el F1 baja mucho, ideal: 20

In [21]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    ros = RandomOverSampler(random_state=0)
    x_train,y_train = ros.fit_resample(x_train,y_train)
    GBR = gbr(max_depth=20).fit(x_train,y_train.values.ravel())
    
    print(GBR.score(x_train,y_train))
    print(GBR.score(x_test,y_test))
    print("Siguiente fold")

1.0
0.7639263425533555
ESPACIO
1.0
0.7620386778642423
ESPACIO
1.0
0.7646582941675013
ESPACIO


In [22]:
from sklearn.metrics import classification_report, confusion_matrix 
print(classification_report(y_test,GBR.predict(x_test)))
print(confusion_matrix(y_test,GBR.predict(x_test)))

              precision    recall  f1-score   support

          -1       0.77      0.76      0.77      7554
           0       0.77      0.80      0.79     13812
           1       0.73      0.66      0.69      4592

    accuracy                           0.76     25958
   macro avg       0.76      0.74      0.75     25958
weighted avg       0.76      0.76      0.76     25958

[[ 5740  1756    58]
 [ 1672 11100  1040]
 [   32  1551  3009]]


In [23]:
GBR.feature_importances_

array([0.03627609, 0.04605215, 0.03696503, 0.04957496, 0.00857467,
       0.11034763, 0.05557181, 0.19140938, 0.04524768, 0.00418963,
       0.00513011, 0.00436226, 0.00417437, 0.00491009, 0.00630073,
       0.00357924, 0.00421658, 0.00413618, 0.00407834, 0.00322639,
       0.00407418, 0.00349512, 0.00386387, 0.00432399, 0.00414463,
       0.00363969, 0.00363414, 0.00423162, 0.00363633, 0.00417815,
       0.04653515, 0.03345258, 0.04577703, 0.05213852, 0.03805754,
       0.03717273, 0.03784575, 0.04147567])

### Gradient Boost Sin ROS

In [24]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    GBR = gbr(max_depth=21).fit(x_train,y_train.values.ravel())
    
    print(GBR.score(x_train,y_train))
    print(GBR.score(x_test,y_test))
    print("Siguiente fold")

1.0
0.7610370598659373
Siguiente fold
1.0
0.7630017720933816
Siguiente fold
1.0
0.7605747746359504
Siguiente fold


In [25]:
from sklearn.metrics import classification_report, confusion_matrix 

print(classification_report(y_test,GBR.predict(x_test)))
print(confusion_matrix(y_test,GBR.predict(x_test)))

              precision    recall  f1-score   support

          -1       0.77      0.75      0.76      7554
           0       0.76      0.81      0.79     13812
           1       0.74      0.62      0.68      4592

    accuracy                           0.76     25958
   macro avg       0.76      0.73      0.74     25958
weighted avg       0.76      0.76      0.76     25958

[[ 5669  1832    53]
 [ 1654 11208   950]
 [   35  1691  2866]]


In [26]:
x_train.shape

(51916, 38)

In [27]:
GBR.feature_importances_

array([0.0356302 , 0.04723631, 0.04678831, 0.04498586, 0.00993346,
       0.07633945, 0.06790728, 0.16808713, 0.05750552, 0.00510533,
       0.00663703, 0.00572011, 0.005462  , 0.00562992, 0.00732973,
       0.00341671, 0.00357968, 0.00448362, 0.00411965, 0.00331586,
       0.0041275 , 0.00390479, 0.00360375, 0.0044071 , 0.00393513,
       0.00379058, 0.00383082, 0.00394383, 0.0039095 , 0.00428072,
       0.0558567 , 0.03405101, 0.04859932, 0.054957  , 0.04076862,
       0.03812402, 0.03885798, 0.03983846])

### HistGradientBoostingClassifier

#### Depth mayor que 50 no cambia nada

##### Mejora un poco con ROS el "1" .55 -> .61  pero empeora el "0"   .75  -> .67


In [28]:
from sklearn.ensemble import HistGradientBoostingClassifier as HSBG

from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    ros = RandomOverSampler(random_state=0)
    x_train,y_train = ros.fit_resample(x_train,y_train)
    HBG = HSBG(max_depth=80,l2_regularization=0.05).fit(x_train,y_train.values.ravel())
    
    print(HBG.score(x_train,y_train))
    print(HBG.score(x_test,y_test))
    print("Siguiente fold")

0.772235265787731
0.6725094383234456
Siguiente fold
0.7709782608695652
0.6617613067262501
Siguiente fold
0.7656748972681151
0.6726635334001079
Siguiente fold


In [29]:
from sklearn.metrics import classification_report, confusion_matrix 
print(classification_report(y_test,HBG.predict(x_test)))
print(confusion_matrix(y_test,HBG.predict(x_test)))

              precision    recall  f1-score   support

          -1       0.66      0.79      0.72      7554
           0       0.80      0.58      0.67     13812
           1       0.51      0.76      0.61      4592

    accuracy                           0.67     25958
   macro avg       0.65      0.71      0.67     25958
weighted avg       0.71      0.67      0.67     25958

[[5956 1073  525]
 [2932 8004 2876]
 [ 116  975 3501]]


## Con Log Reg
### con ROS

iter = 200-600 .59, .52

### Sin ROS

iter = 600    .57, .56


In [116]:
kf = KFold(n_splits=4)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    ros = RandomOverSampler(random_state=0)
    x_train,y_train = ros.fit_resample(x_train,y_train)
    x_test,y_test = ros.fit_resample(x_test,y_test)
    LREG = LogisticRegression(max_iter=500).fit(x_train,y_train)
    print(LREG.score(x_train,y_train))
    print(LREG.score(x_test,y_test))

C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5910804154620409
0.5906087853298527


C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.5906650808447717
0.5923388653029719


C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.592513988037816
0.5893654618473896


C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.5943847457263582
0.5974400923876432


C:\Users\CLIENTE\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [117]:
print(classification_report(y_test,LREG.predict(x_test)))
print(confusion_matrix(y_test,LREG.predict(x_test)))

              precision    recall  f1-score   support

          -1       0.72      0.66      0.69     10391
           0       0.47      0.37      0.42     10391
           1       0.59      0.76      0.66     10391

    accuracy                           0.60     31173
   macro avg       0.59      0.60      0.59     31173
weighted avg       0.59      0.60      0.59     31173

[[6829 2144 1418]
 [2360 3867 4164]
 [ 297 2166 7928]]


### Con GradientBoostClass ROS
#### max_depth = 10
###### Resultado es similar al resto de GB

In [30]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)

for train_index, test_index in kf.split(X):
    x_train, x_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = Y.iloc[train_index], Y.iloc[test_index]
    ros = RandomOverSampler(random_state=0)
    x_train,y_train = ros.fit_resample(x_train,y_train)
    GBR = gbr(max_depth=10).fit(x_train,y_train.values.ravel())
    
    print(GBR.score(x_train,y_train))
    print(GBR.score(x_test,y_test))
    print("Siguiente fold")

0.9367647944133406
0.7485168348871254
Siguiente fold
0.9322101449275362
0.7373449418291086
Siguiente fold
0.9315763469626309
0.7465521226596811
Siguiente fold


In [31]:
from sklearn.metrics import classification_report, confusion_matrix 
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

              precision    recall  f1-score   support

          -1       0.74      0.79      0.77      7554
           0       0.81      0.72      0.76     13812
           1       0.63      0.75      0.68      4592

    accuracy                           0.75     25958
   macro avg       0.72      0.76      0.74     25958
weighted avg       0.75      0.75      0.75     25958

[[6003 1298  253]
 [2083 9910 1819]
 [  46 1080 3466]]


El RandomForest lo hace mejor que el resto con max_depth=50, n_estimators=50
El segundo mejor es el GradientBoost y el depth ideal es de 20-25. Sin embargo, demora mucho.
Le sigue el HistGradientBoosting, que es más rápido pero no obtiene resultados adecuados.